image: hipay/gitlab-ci-base:jessie

stages:
 - test

phpunit:
  stage: test
  before_script:
    - composer install
  script:
    - phpunit -c tests/unit/phpunit.xml
  allow_failure: false
  tags:
    - pi-ecommerce
